#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
        [0] = LAYOUT(
            KC_BSPC, KC_PSLS, KC_PAST, KC_PMNS, 
            KC_P7, KC_P8, KC_P9, KC_PPLS,
            KC_P4, KC_P5, KC_P6, KC_NO, 
            KC_P1, KC_P2, KC_P3, KC_PENT, 
            MO(1), KC_P0, KC_PDOT, KC_NO),

        [1] = LAYOUT(
            KC_DEL, KC_MUTE, KC_F24, KC_CALC, 
            KC_NO, KC_NO, KC_NO, KC_NO,
            KC_NO, KC_NO, KC_NO, KC_NO,
            KC_NO, KC_NO, KC_NO, KC_NUM, 
            KC_TRNS, KC_NO, KC_NO, KC_NO)
};